# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
 :pamvm => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "pam-net"}
               ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        #box.vm.provision "ansible" do |ansible|
        #  ansible.playbook = "playbook.yml"
        #  ansible.become = "true"
        #end

        case boxname.to_s
          when "pamvm"
            box.vm.provision "shell", inline: <<-SHELL
              yum install -y epel-release 
              yum install -y pam_script
              groupadd admin
              useradd pamuser
              usermod -a -G admin pamuser
              echo "pamuser:pamuser" | chpasswd
              sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              systemctl restart sshd
            SHELL
        end

      end

  end
  
end

