# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
 :pamvm => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "pam-net"}
               ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        #box.vm.provision "ansible" do |ansible|
        #  ansible.playbook = "playbook.yml"
        #  ansible.become = "true"
        #end

        case boxname.to_s
          when "pamvm"
            box.vm.provision "shell", inline: <<-SHELL
              yum install -y epel-release 
              yum install -y pam_script
              groupadd admin
              useradd pamuser
              usermod -a -G admin pamuser
              echo "pamuser:pamuser" | chpasswd
              sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              echo "auth       required     pam_script.so" >> /etc/pam.d/sshd
              cat <<'EOT' > /etc/pam_script
#!/bin/bash

# Check if User in "admin" group
USER=$PAM_USER

if [[ `grep $USER /etc/group | grep 'admin'` ]]
then
  exit 1
fi

# Check if today is free day or a holiday.
DAY=`date +"%u"`
MDAY=`date +"%d%m"`

if [[ $DAY == "6" || $DAY == "7" ]]
then
  echo "Hey, it's weekend! Go home!"
  exit 1
elif [[ $MDAY == "0101" || $MDAY == "0803" || $MDAY == "2302" ]]
then
  echo "Hey! Today is holiday! Go HOME!"
  exit 1
else
  echo "OK, today's work day. Go and work!"
  exit 0
fi
EOT
              chmod +x /etc/pam_script
              systemctl restart sshd
            SHELL
        end

      end

  end
  
end

