---
- hosts: inetRouter
  become: yes
  tasks:
    - name: Set ip forwarding = 1
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
  
    - name: iptables config
      shell: 
        cmd: |
          cat <<EOT | iptables-restore
          *filter
          :INPUT DROP [0:0]
          :FORWARD ACCEPT [12816:43815755]
          :OUTPUT ACCEPT [106:11577]
          :SSH-INPUT - [0:0]
          :SSH-INPUTTWO - [0:0]
          :TRAFFIC - [0:0]
          -A INPUT -j TRAFFIC
          -A SSH-INPUT -m recent --set --name SSH1 --mask 255.255.255.255 --rsource -j DROP
          -A SSH-INPUTTWO -m recent --set --name SSH2 --mask 255.255.255.255 --rsource -j DROP
          -A TRAFFIC -p icmp -m icmp --icmp-type any -j ACCEPT
          -A TRAFFIC -m state --state RELATED,ESTABLISHED -j ACCEPT
          -A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 22 -m recent --rcheck --seconds 30 --name SSH2 --mask 255.255.255.255 --rsource -j ACCEPT
          -A TRAFFIC -p tcp -m state --state NEW -m tcp -m recent --remove --name SSH2 --mask 255.255.255.255 --rsource -j DROP 
          -A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 9991 -m recent --rcheck --name SSH1 --mask 255.255.255.255 --rsource -j SSH-INPUTTWO
          -A TRAFFIC -p tcp -m state --state NEW -m tcp -m recent --remove --name SSH1 --mask 255.255.255.255 --rsource -j DROP
          -A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 7777 -m recent --rcheck --name SSH0 --mask 255.255.255.255 --rsource -j SSH-INPUT
          -A TRAFFIC -p tcp -m state --state NEW -m tcp -m recent --remove --name SSH0 --mask 255.255.255.255 --rsource -j DROP
          -A TRAFFIC -p tcp -m state --state NEW -m tcp --dport 8881 -m recent --set --name SSH0 --mask 255.255.255.255 --rsource -j DROP
          -A TRAFFIC -j DROP
          COMMIT
          *nat
          :PREROUTING ACCEPT [189:12684]
          :INPUT ACCEPT [1:60]
          :OUTPUT ACCEPT [21:1660]
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
          COMMIT
          EOT
        
    - name: Tune System 
      shell: |
        ip route add 192.168.0.0/16 via 192.168.255.3
        echo "vagrant:vagrant" | chpasswd
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config

    - name: Service sshd restart
      service:
        name: sshd
        state: restarted

- hosts: inetRouter2
  become: yes
  tasks:
    - name: Set ip forwarding = 1
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: iptables config
      shell: 
        cmd: |
          cat <<EOT | iptables-restore
          *filter
          :INPUT ACCEPT [142:8307]
          :FORWARD ACCEPT [46:9408]
          :OUTPUT ACCEPT [76:5898]
          -A FORWARD -d 192.168.0.2/32 -i eth0 -o eth1 -p tcp -m tcp --dport 80 -j ACCEPT
          COMMIT
          *nat
          :PREROUTING ACCEPT [0:0]
          :INPUT ACCEPT [0:0]
          :OUTPUT ACCEPT [5:374]
          :POSTROUTING ACCEPT [0:0]
          -A PREROUTING -d 10.0.2.15/32 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.168.0.2:80
          -A PREROUTING -d 10.0.2.15/32 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.168.0.2:80
          -A OUTPUT -d 10.0.2.15/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.0.2
          -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
          -A POSTROUTING -d 192.168.0.2/32 -p tcp -m tcp --dport 80 -j SNAT --to-source 192.168.255.2
          COMMIT
          EOT

    - name: Tune System 
      shell: |
        ip route add 192.168.0.0/16 via 192.168.255.3
        echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

- hosts: centralRouter
  become: yes
  tasks:
    - name: Set ip forwarding = 1
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Set ip forwarding = 1
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Tune System 
      shell: |
        echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

    - name: Install nmap
      yum:
        name: nmap
        state: present
        update_cache: yes

    - name: Restart network
      systemd:
        state: restarted
        daemon_reload: yes
        name: network

- hosts: centralServer
  become: yes
  tasks:
    - name: Tune System 
      shell: |
        echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

    - name: Restart network
      systemd:
        state: restarted
        daemon_reload: yes
        name: network

    - name: Install epel-release
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: Install nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Restart nginx
      systemd:
        state: started
        enabled: yes
        name: nginx

