#!/bin/bash

for i in $(ls -d /proc/[0-9]* | sort -V);
  do
     PID="$(basename $i)"
     if [ -f "$i/cmdline" ] && [ "`cat $i/cmdline | awk 'END { print (NR > 0 && NF > 0) ? "1" : "0"}'`" == "1" ]
     then
       echo -ne "$(basename $i)\t" \
       && awk '{ printf $3 "\t"}' $i/stat 
       awk '{ if(match($NF,/[a-z]+/)) printf $NF; }' $i/cmdline;
     fi
done

